# Generated by Django 5.0.6 on 2026-07-23 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('color', models.CharField(default='#0E9F6E', max_length=20, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'دستهٔ جلسه',
                'verbose_name_plural': 'دسته\u200cهای جلسه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('capacity', models.CharField(blank=True, max_length=40, verbose_name='ظرفیت')),
                ('is_online', models.BooleanField(default=False, verbose_name='آنلاین')),
            ],
            options={
                'verbose_name': 'محل جلسه',
                'verbose_name_plural': 'محل\u200cهای جلسه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('kind', models.CharField(choices=[('internal', 'داخلی'), ('bank', 'بانک'), ('regulator', 'رگولاتور'), ('partner', 'شریک')], default='partner', max_length=16, verbose_name='نوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('ceo', 'مدیرعامل'), ('member', 'کاربر عادی')], default='member', max_length=10, verbose_name='سطح دسترسی')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شمارهٔ تماس')),
                ('color', models.CharField(blank=True, help_text='گرادیان "start,end"', max_length=40, verbose_name='رنگ آواتار')),
                ('is_external', models.BooleanField(default=False, verbose_name='مهمان خارجی')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='ارسال پیامک')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='meetings.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'کاربر/فرد',
                'verbose_name_plural': 'کاربران/افراد',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False, verbose_name='متصل')),
                ('calendar_id', models.CharField(blank=True, max_length=255, verbose_name='شناسهٔ کلندر موازی')),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اتصال Google Calendar',
                'verbose_name_plural': 'اتصال\u200cهای Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('meeting_type', models.CharField(choices=[('board', 'هیئت مدیره'), ('external', 'با مهمان خارجی'), ('internal', 'داخلی'), ('online', 'آنلاین')], default='internal', max_length=12, verbose_name='نوع')),
                ('status', models.CharField(choices=[('confirmed', 'تأییدشده'), ('pending', 'در انتظار'), ('cancelled', 'لغوشده'), ('done', 'برگزارشده')], default='confirmed', max_length=12, verbose_name='وضعیت')),
                ('start', models.DateTimeField(verbose_name='شروع')),
                ('end', models.DateTimeField(verbose_name='پایان')),
                ('google_synced', models.BooleanField(default=False, verbose_name='همگام با Google Calendar')),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.category', verbose_name='دسته\u200cبندی')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.location', verbose_name='محل')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='مدت (دقیقه)')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'بند دستور جلسه',
                'verbose_name_plural': 'دستور جلسه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False, verbose_name='مهمان خارجی')),
                ('response', models.CharField(choices=[('accepted', 'پذیرفته'), ('pending', 'در انتظار'), ('declined', 'رد شده')], default='pending', max_length=10, verbose_name='پاسخ دعوت')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شرکت\u200cکنندهٔ جلسه',
                'verbose_name_plural': 'شرکت\u200cکنندگان جلسه',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingParticipant', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکنندگان'),
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_minutes', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_set', to='meetings.meeting')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_minutes', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکننده (خالی = عمومی)')),
            ],
            options={
                'verbose_name': 'صورت\u200cجلسه',
                'verbose_name_plural': 'صورت\u200cجلسه\u200cها',
                'unique_together': {('meeting', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='MinuteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('note', 'یادداشت'), ('decision', 'تصمیم'), ('task', 'تسک'), ('reminder', 'یادآور'), ('call', 'تماس تلفنی'), ('letter', 'نامه'), ('file', 'فایل')], max_length=12, verbose_name='نوع')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان یادآوری')),
                ('call_with', models.CharField(blank=True, max_length=120, verbose_name='با چه کسی')),
                ('call_phone', models.CharField(blank=True, max_length=20, verbose_name='شمارهٔ تماس')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meetings.minutes')),
            ],
            options={
                'verbose_name': 'آیتم صورت\u200cجلسه',
                'verbose_name_plural': 'آیتم\u200cهای صورت\u200cجلسه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('letter', 'نامه'), ('file', 'فایل')], default='file', max_length=10, verbose_name='نوع')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='فایل')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام نمایشی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.minuteentry')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.minutes')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('meeting', 'جلسه'), ('invite', 'دعوت\u200cنامه'), ('task', 'تسک'), ('reminder', 'یادآور')], max_length=10, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='متن')),
                ('remind_at', models.DateTimeField(verbose_name='زمان اعلان (۳۰ دقیقه قبل)')),
                ('delivered_in_app', models.BooleanField(default=False, verbose_name='نمایش در پنل')),
                ('delivered_sms', models.BooleanField(default=False, verbose_name='ارسال پیامک')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='meetings.minuteentry')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='meetings.organization', verbose_name='سازمان'),
        ),
    ]
