# Generated by Django 5.0.6 on 2026-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuteentry',
            name='due_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='مهلت (متن واردشده)'),
        ),
        migrations.AddField(
            model_name='minuteentry',
            name='remind_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='زمان یادآوری (متن واردشده)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments/%Y/%m/', verbose_name='فایل'),
        ),
    ]
