# Generated by Django 5.0.6 on 2026-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_minuteentry_due_text_minuteentry_remind_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شمارهٔ موبایل')),
                ('code', models.CharField(max_length=8, verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
            ],
            options={
                'verbose_name': 'کد ورود',
                'verbose_name_plural': 'کدهای ورود',
                'ordering': ['-created_at'],
            },
        ),
    ]
