# Generated by Django 5.0.6 on 2026-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='لینک/شناسهٔ Google Meet'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('critical', 'خیلی زیاد')], default='normal', max_length=10, verbose_name='اولویت'),
        ),
    ]
