# Generated by Django 5.0.6 on 2026-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_organization_kind_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], default='in_person', max_length=12, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='minuteentry',
            name='due_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='مهلت (متن آزاد — فقط دادهٔ قدیمی)'),
        ),
    ]
