# Generated by Django 5.0.6 on 2026-07-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_meeting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meet_link',
            field=models.CharField(blank=True, help_text='نشانی کامل هر سرویسی — Google Meet، اسکای\u200cروم، Zoom، Adobe Connect و…', max_length=500, verbose_name='لینک جلسهٔ آنلاین'),
        ),
    ]
