# Generated by Django 5.0.6 on 2026-08-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_meet_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_minutes', models.PositiveIntegerField(default=60, help_text='چند دقیقه پیش از شروع جلسه پیامک برود', verbose_name='فاصله تا شروع (دقیقه)')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('send_error', models.CharField(blank=True, max_length=120, verbose_name='خطای ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'یادآور جلسه',
                'verbose_name_plural': 'یادآورهای جلسه',
                'indexes': [models.Index(fields=['sent_at'], name='meetings_me_sent_at_ddbdae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingreminder',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='uniq_reminder_per_user'),
        ),
    ]
