# Generated by Django 5.0.6 on 2026-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meetingreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreminder',
            name='send_error',
            field=models.CharField(blank=True, max_length=200, verbose_name='خطای ارسال'),
        ),
    ]
