# Generated by Django 5.0.6 on 2026-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meetingreminder_send_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreminder',
            name='provider_msg_id',
            field=models.CharField(blank=True, help_text='برای پیگیری گزارش تحویل در پنل پیامک', max_length=40, verbose_name='شناسهٔ پیام نزد سرویس'),
        ),
    ]
