# Generated by Django 5.0.6 on 2026-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meetingreminder_provider_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreminder',
            name='delivery_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی تحویل'),
        ),
        migrations.AddField(
            model_name='meetingreminder',
            name='delivery_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد تحویل'),
        ),
    ]
