# Generated by Django 5.0.6 on 2026-08-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meetingreminder_delivery_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, verbose_name='نشانی کامل'),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='دلیل لغو'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_meetings', to=settings.AUTH_USER_MODEL, verbose_name='لغوکننده'),
        ),
        migrations.AddField(
            model_name='minuteentry',
            name='agenda_item',
            field=models.ForeignKey(blank=True, help_text='اختیاری — این آیتم ذیل کدام بند مطرح شد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='meetings.agendaitem', verbose_name='بند دستور جلسه'),
        ),
    ]
