# Generated by Django 5.0.6 on 2026-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_location_address_location_lat_location_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuteentry',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش'),
        ),
    ]
