# Generated by Django 5.0.6 on 2026-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_drop_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ادمین'), ('ceo', 'مدیرعامل'), ('executive', 'مدیر اجرایی'), ('member', 'کاربر عادی')], default='member', max_length=10, verbose_name='سطح دسترسی'),
        ),
    ]
