# Generated by Django 5.0.6 on 2026-09-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_executive_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='google_synced',
        ),
        migrations.DeleteModel(
            name='GoogleCalendarConnection',
        ),
    ]
