# Generated by Django 5.0.6 on 2026-09-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_drop_google_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write_minutes', models.BooleanField(default=False, help_text='پیش\u200cفرض خاموش؛ فقط صاحب تقویم می\u200cتواند روشنش کند.', verbose_name='اجازهٔ نوشتن صورت\u200cجلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares_out', to=settings.AUTH_USER_MODEL, verbose_name='صاحب تقویم')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares_in', to=settings.AUTH_USER_MODEL, verbose_name='بیننده')),
            ],
            options={
                'verbose_name': 'اشتراک تقویم',
                'verbose_name_plural': 'اشتراک\u200cهای تقویم',
                'ordering': ['owner_id', 'viewer_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarshare',
            constraint=models.UniqueConstraint(fields=('owner', 'viewer'), name='uniq_calendar_share'),
        ),
        migrations.AddConstraint(
            model_name='calendarshare',
            constraint=models.CheckConstraint(check=models.Q(('owner', models.F('viewer')), _negated=True), name='calendar_share_not_self'),
        ),
    ]
