# Generated by Django 5.0.6 on 2026-09-06 08:13

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meetings', '0017_calendar_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.TextField(verbose_name='شناسهٔ رویداد')),
                ('remote_change_key', models.CharField(blank=True, max_length=255, verbose_name='changeKey')),
                ('ical_uid', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='iCalUId')),
                ('is_authoritative', models.BooleanField(default=False, verbose_name='نسخهٔ مرجع')),
                ('response', models.CharField(blank=True, max_length=20, verbose_name='پاسخ دعوت')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی')),
            ],
            options={
                'verbose_name': 'رویداد Outlook',
                'verbose_name_plural': 'رویدادهای Outlook',
            },
        ),
        migrations.CreateModel(
            name='OutlookMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='نشانی صندوق')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('delta_link', models.TextField(blank=True, verbose_name='نشانهٔ delta')),
                ('delta_page_link', models.TextField(blank=True, verbose_name='صفحهٔ ناتمام')),
                ('window_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع بازه')),
                ('window_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان بازه')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین واکشی موفق')),
                ('retry_after', models.DateTimeField(blank=True, null=True, verbose_name='تلاش دوباره پس از')),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, verbose_name='خطاهای پیاپی')),
                ('last_error', models.CharField(blank=True, max_length=300, verbose_name='آخرین خطا')),
            ],
            options={
                'verbose_name': 'صندوق Outlook',
                'verbose_name_plural': 'صندوق\u200cهای Outlook',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OutlookUnmappedAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='نشانی')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='نام نمایشی')),
                ('seen_count', models.PositiveIntegerField(default=1, verbose_name='دفعات دیده\u200cشدن')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نشانی ناشناخته',
                'verbose_name_plural': 'نشانی\u200cهای ناشناخته',
                'ordering': ['-seen_count'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='local_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تغییر محلی'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='محل (متن آزاد)'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_conflict_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تعارض'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_conflict_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='شرح تعارض'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_dirty',
            field=models.BooleanField(default=False, verbose_name='در صف ارسال به Outlook'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_readonly',
            field=models.BooleanField(default=False, verbose_name='فقط\u200cخواندنی (برگزارکنندهٔ بیرونی)'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_synced',
            field=models.BooleanField(default=False, verbose_name='همگام با Outlook'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outlook_uid',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='شناسهٔ Outlook'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='uniq_user_email_ci'),
        ),
        migrations.AddField(
            model_name='outlookevent',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_events', to='meetings.meeting', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='outlookmailbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_mailbox', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='outlookevent',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.outlookmailbox', verbose_name='صندوق'),
        ),
        migrations.AddConstraint(
            model_name='outlookunmappedattendee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_unmapped_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='outlookevent',
            constraint=models.UniqueConstraint(fields=('mailbox', 'remote_id'), name='uniq_outlook_event'),
        ),
        migrations.AddConstraint(
            model_name='outlookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_authoritative', True)), fields=('meeting',), name='uniq_outlook_authoritative'),
        ),
    ]
