# Generated by Django 5.0.6 on 2026-09-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0018_outlook_sync'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('outlook_uid', ''), _negated=True), fields=('outlook_uid',), name='uniq_meeting_outlook_uid'),
        ),
    ]
